### ISSUE TITLE
I found a bug

### ISSUE THREAD

**Issue by sedatcakir** [lewishowles/sketch-replace-colour#12] opened 2016-11-16 09:13 UTC
There is a problem with the extension. Color change is not working. Example: select the element to change the color. I am writing the code for the color that will change the window. The plugin does not apply all my code coloring. It's making a white color.

Sketch 4.1

**Comment by lewishowles** [comment] 2016-11-16 09:14
Do you have the latest version of the plugin (updated last night)? There was a bug in the previous version that was fixed.

**Comment by sedatcakir** [comment] 2016-11-16 09:25
hi, plugin updated. Here are the error videos.
https://youtu.be/15P-NDA3L_s

**Comment by lewishowles** [comment] 2016-11-16 09:29
I've just reinstalled the plugin and tested and it seems to be working OK for me doing the same thing. If you go to Plugins -> Manage Plugins do you see the same version number?

![image](https://cloud.githubusercontent.com/assets/1140753/20341669/1ab0b52a-abdf-11e6-8e0b-3d17ae8f309f.png)

**Comment by sedatcakir** [comment] 2016-11-16 10:28
update: 2.0.3
<img width="465" alt="ekran resmi 2016-11-16 13 27 10" src="https://cloud.githubusercontent.com/assets/1352113/20343702/1eed1b7e-abf8-11e6-9e23-f9f9fd64ca4b.png">

**Comment by tonnyma** [comment] 2016-11-16 23:32
I am experiencing the same thing, my text color fill changes to 10FF10FF. Also on 2.0.3. Sketch version: Version 41 (35326). 
See attached.

![screen shot 2016-11-16 at 3 31 10 pm](https://cloud.githubusercontent.com/assets/11724043/20370121/cb1fb082-ac11-11e6-939d-e727214772e3.png)

**Comment by lewishowles** [comment] 2016-11-17 20:59
Hi guys,

Sorry for the delay. I think I finally found the issue, and this should be  fixed in 2.0.4. Let me know if that works better now.

**Closed as completed** 2016-11-17 20:58 UTC

**Comment by tonnyma** [comment] 2016-11-17 21:04
thanks for the quick fix. I can confirm that it worked!
